### ISSUE TITLE
How to get the count (length) of a table

### ISSUE THREAD

**Issue by patte** [get-convex/convex-backend#10]
Hey I'm evaluation convex for an upcoming project and I need to count all entries in a table (or by index). There doesn't seem to be a dedicated api function, `collect()` doesn't work for big tables and multiple `paginate()` are not supported in one function. How can a function count a table independent of it's size? For big tables an estimate would be sufficient.

```ts
export const count = query({
  handler: async (ctx) => {
    // Server Error
    // Uncaught Error: Too many documents read in a single function execution (limit: 16384).
    // Consider using smaller limits in your queries, paginating your queries,
    // or using indexed queries with a selective index range expressions.
    return (await ctx.db.query("messages").collect()).length;

    // Unexpected Application Error!
    // Error: This query or mutation function ran multiple paginated queries.
    // Convex only supports a single paginated query in each function.
    // let isDone = false;
    // let continueCursor = null;
    // let page;
    // let count = 0;
    // while (!isDone) {
    //   ({ continueCursor, isDone, page } = await ctx.db
    //     .query("messages")
    //     .paginate({
    //       numItems: 1000,
    //       cursor: continueCursor,
    //     }));
    //   console.log("got", page.length);
    //   count += page.length;
    // }
    // return count;
  },
});
```

**Comment by nipunn1313** [comment]
The query builder has an undocumented `.count()` API that you can use in a pinch
https://github.com/get-convex/convex-js/blob/main/src/server/query.ts#L103

It's not part of our 1.0 API, so we might change how to get at it.

The reason we are holding off on stabilizing it, is because we can only do the operation efficiently on full tables (not indexed queries).

For the use-case you have above, it should work fine.
If you just want to see them, you can see it on the dashboard (dashboard.convex.dev) where it looks like this. This is powered by the `.count` anyway (see https://github.com/get-convex/convex-backend/blob/eb6329030009051e330392bc47e286e2e30056d7/npm-packages/system-udfs/convex/_system/frontend/tableSize.ts#L35).
![image](https://github.com/user-attachments/assets/885743bf-b41f-4f58-9c0e-4b9cddcca33a)

**Comment by nipunn1313** [comment]
if you have a more semantically important use case - we'd love to hear about it - as it may help us design the API for `.count()` better.

**Comment by patte** [comment]
That works and it's plenty fast 🎉 
```typescript
export const count = query({
  handler: async (ctx) => {
    // @ts-expect-error count is internal -  https://github.com/get-convex/convex-backend/issues/10
    return await ctx.db.query("messages").count();
  },
});
 ```
 Thank you very much!

**Comment by AyoParadis** [comment]
> The query builder has an undocumented `.count()` API that you can use in a pinch https://github.com/get-convex/convex-js/blob/main/src/server/query.ts#L103
> 
> It's not part of our 1.0 API, so we might change how to get at it.
> 
> The reason we are holding off on stabilizing it, is because we can only do the operation efficiently on full tables (not indexed queries).
> 
> For the use-case you have above, it should work fine. If you just want to see them, you can see it on the dashboard (dashboard.convex.dev) where it looks like this. This is powered by the `.count` anyway (see
> 
> https://github.com/get-convex/convex-backend/blob/eb6329030009051e330392bc47e286e2e30056d7/npm-packages/system-udfs/convex/_system/frontend/tableSize.ts#L35
> 
> ).
> ![image](https://private-user-images.githubusercontent.com/1300387/363776472-885743bf-b41f-4f58-9c0e-4b9cddcca33a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTQ3NDUsIm5iZiI6MTczMjA5NDQ0NSwicGF0aCI6Ii8xMzAwMzg3LzM2Mzc3NjQ3Mi04ODU3NDNiZi1iNDFmLTRmNTgtOWMwZS00YjljZGRjY2EzM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMDkyMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q3ODBkMWM4ZDdjM2RhNjNkYThhNDNlNDczMmUyZDU2NDZiMDI5OWU1OTFiMzc1ZWJhYzEwMTdkZDI0M2NhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mC7Xk92aq4Q5Qs6d8wMJ7CdkCw6bsOw6iRib8yxnk0g)

will something like this be possible soon?

````js
ctx.db
.query("eventMoment")
.withIndex("by_creatorId",(q) => q.eq("creatorId",partnerId))
.filter((q) => q.eq(q.field("hasPartnerSeen"),false))
.count(),
````

or

````js
ctx.db
.query("eventMoment")
withIndex("by_creatorId_hasPartnerSeen",(q) => q.eq("creatorId",partnerId).eq("hasPartnerSeen",false)).count(),
````

**Comment by nipunn1313** [comment]
@AyoCodess 

Try 
```typescript
const entries = ctx.db
  .query("eventMoment")
  .withIndex("by_creatorId",(q) => q.eq("creatorId",partnerId))
  .filter((q) => q.eq(q.field("hasPartnerSeen"),false))
  .collect();
const count = entries.length;
```

This fetches all the entries along the index, which is fine if you have 100s to 1000s (maybe even 10000s) of entries in the table. If it starts reaching into 100000s, your query might time out - then I'd recommend using the aggregates component
https://www.convex.dev/components/aggregate

Aggregates component tracks this information at write time so that it's easy to access at read time.

**Comment by AyoParadis** [comment]
> @AyoCodess 
> 
> 
> 
> Try 
> 
> ```typescript
> 
> const entries = ctx.db
> 
>   .query("eventMoment")
> 
>   .withIndex("by_creatorId",(q) => q.eq("creatorId",partnerId))
> 
>   .filter((q) => q.eq(q.field("hasPartnerSeen"),false))
> 
>   .collect();
> 
> const count = entries.length;
> 
> ```
> 
> 
> 
> This fetches all the entries along the index, which is fine if you have 100s to 1000s (maybe even 10000s) of entries in the table. If it starts reaching into 100000s, your query might time out - then I'd recommend using the aggregates component
> 
> https://www.convex.dev/components/aggregate
> 
> 
> 
> Aggregates component tracks this information at write time so that it's easy to access at read time.

Thanks 👍🏾
