### ISSUE TITLE
How to delete specific filed from table - convex schema

### ISSUE THREAD

**Issue by hientt1803** [get-convex/convex-backend#4]
- I'm currently working on my Next.js project and using convex as a database 
- I change "tag_id" and "user_id" to "tagId, userId" and
- I tryna delete two column called "tag_id" and "user_id" from my post table.

- But i can't figure out how to completely delete the column. i have read some tutorial about migration and it just instruct change the type to optional or set the null, "" value to that column.

> [!NOTE]
> My table already has some data
> And i already change "tag_id", "user_id" value to ""
> Sorry about my bad english.

> Please can anyone help me figure out `how to safely delete column in this table but not effect data`

**- This is my post chema.ts**

```
posts: defineTable({
      slug: v.string(),
      title: v.string(),
      excerpt: v.string(),
      desc: v.string(),
      image: v.optional(v.string()),
      views: v.number(),
      status: POST_STATUS,
      userId: v.optional(v.id("users")),
      tagId: v.optional(v.id("tags")),
      user_id: v.optional(v.string()),
      tag_id: v.optional(v.string()),
    })
      .searchIndex("search_title_desc_slug", {
        searchField: "title",
        filterFields: ["title", "desc", "slug"],
      });

```

**Comment by nipunn1313** [comment]
Come find us on our discord https://convex.dev/community - there's a lot more folks paying attention there and can help you out.
The dashboard (dashboard.convex.dev) is pretty excellent for making changes to the data in your tables.

Closing this out - and hopefully you can get some help over on our discord.
