### ISSUE TITLE
Can i use convex with kotlin

### ISSUE THREAD

**Issue by calebgrimah** [get-convex/convex-backend#8]
Can i use kotlin to connect to the convex backend or its javascript only?

**Comment by jouyang19** [comment]
You might be able to connect it with react native, but I never played with native, so I'm not sure.

**Comment by nipunn1313** [comment]
we're working on a kotlin SDK for Android. It's really fresh.

Would you be interested in trying out an early version? We can get it to you.

**Comment by thomasballinger** [comment]
This is out! See https://docs.convex.dev/client/android and https://docs.convex.dev/quickstart/android.
